config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'auth/:provider/callback', to: 'sessions#omni'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/signup',  to: 'users#create'
  get '/admin/AllProperties', to: 'properties#adminUser'
  get '/search', to: 'static_pages#search'
  resources :users, :admins do
    resources :properties, :reviews
  end

  resources :properties do
    resources :reviews, :favourites
  end
  resources :admins do
    resources :users
    get :reviews, to: 'reviews#index'
  end
  resources :reviews do
    get 'approval'
    patch 'approve'
    get 'userReview', on: :collection
  end
  resources :reviews, :properties, :favourites
    
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :property
  validates :property_id, uniqueness: { scope: :user_id, message: ":You have already Added this Property in your Favourite List" }
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @user = current_user
  end

  def create
    @property = Property.find(params[:property_id])
    @favourite = @property.favourites.create(params.require(:favourite).permit(:interested))
    @favourite.user= current_user
    if @favourite.save
      msg = "Property added to your favourite List"
      if @favourite.interested
        flash[:success] = msg + " and Property is marked as Interested"
        UserMailer.property_interested(@property,current_user).deliver_now
      else
        flash[:success] = msg + " and Property is not marked as Interested"
      end
      redirect_to favourites_path
    else
      flash[:error] = @favourite.errors.full_messages.first
      redirect_to favourites_path
    end
  end

  def update
    @favourite = Favourite.find(params[:id])
    if @favourite.update_attributes(params.require(:favourite).permit(:interested))
      msg = "Property Updated to your favourite List"
      if @favourite.interested
        flash[:success] = msg + " and Property is marked as Interested"
        UserMailer.property_interested(@favourite.property,current_user).deliver_now
      else
        flash[:success] = msg + " and Property is not marked as Interested"
      end
      redirect_to favourites_path
    else
      flash[:error] = @favourite.errors.full_messages.first
      redirect_to favourites_path
    end
  end

  def destroy
    Favourite.find(params[:id]).destroy
    flash[:success] = "Removed from your Favourite List"
    redirect_to favourites_path
  end

end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/index.html.erb
<% unless @user.favourites.empty? %>
  <table class="table">
    <th>Property</th>
    <th>Interest</th>
    <th>Remove from Favourite List</th>
    <% @user.favourites.each do |f| %>
      <tr>
        <td><%= link_to f.property.title, f.property %></td>
        <% if f.interested %>
          <td>Interested</td>
        <% else %>
          <td>Not Interested</td>
        <% end %>
        <td><%= link_to 'Remove', favourite_path(f), method: :delete, data: { confirm: "Are You Sure? If you Remove your interest over property will also be removed"}%></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h2 class="text-center">You have not marked any property as Interested</h2>
<% end %>