config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'auth/:provider/callback', to: 'sessions#omni'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/signup',  to: 'users#create'
  get '/admin/AllProperties', to: 'properties#adminUser'
  get '/search', to: 'static_pages#search'
  resources :users, :admins do
    resources :properties, :reviews
  end

  resources :properties do
    resources :reviews, :favourites
  end
  resources :admins do
    resources :users
    get :reviews, to: 'reviews#index'
  end
  resources :reviews do
    get 'approval'
    patch 'approve'
    get 'userReview', on: :collection
  end
  resources :reviews, :properties, :favourites
    
end

app/models/property.rb
class Property < ApplicationRecord
  validate :property_owner_type
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :title, presence: true, length: { in: 5..255 }
  validates :description, presence: true, length: { in: 5..1024 }
  validates :owner, presence: true, length: { in: 3..100 }
  validates :contact, presence: true, length: { is: 10 }
  validates :location, presence: true, length: { in: 3..50 }
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validate  :picture_size
  def property_owner_type
    if owner_type == 'I have a Property'
      unless price.present?
        errors.add(:price, "Cant be blank")
      end
      unless area.present?
        errors.add(:area, "Cant be blank")
      end
    end
  end
private
  # Validates the size of an uploaded picture.
 def picture_size
   if picture.size > 5.megabytes
     errors.add(:picture, "should be less than 5MB")
   end
 end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_action :require_login, only: [:home, :show]
  before_action :admin_login, only: [:adminUser]
  before_action :correct_property, only: [:edit, :delete, :update]

  def index
    @user = current_user
  end

  def new
    @user = current_user
    @property = Property.new
  end

  def create
    @user = User.find(params[:user_id])
    @property = @user.properties.create(params.require(:property).permit(:title, :description, :category, :location, :price, :area, :owner, :contact, :info, :bedrooms, :bathrooms, :owner_type, :rooms, :city, :picture))
    if @property.owner_type == "I need a Property"
      @property.status = "Needed"
    end
    if @property.save
      flash[:success] = "Property Submitted"
      redirect_to @property
    else
      render 'new'
    end
  end

  def view
    @property = Property.find(params[:property_id])
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update_attributes(params.require(:property).permit(:title, :description, :category, :location, :price, :area, :owner, :contact, :info, :status, :bedrooms, :bathrooms, :rooms, :city, :picture))
      flash[:success] = "Property Added"
      redirect_to user_property_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    property=Property.find(params[:id])
    visited_property_delete(property)
    property.destroy
    flash[:success] = "Property Deleted"
    redirect_to current_user
  end

  def adminUser
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
    unless current_user == @property.user
      @property.viewers = @property.viewers + 1
      @property.save
    end
    if logged_in?
      unless (current_user == @property.user)
        property_visited(@property)
       UserMailer.property_visited(@property,current_user).deliver_now
      end
    end
    @favourite = Favourite.find_by(user_id: current_user, property_id: @property)
  end

  private
   def correct_property
     @property = Property.find(params[:id])
     unless (current_user.is_admin)
       if current_user != @property.user
         flash[:danger] = "You are Not Authorize to this Property Operations"
         redirect_to root_path
       end
     end
   end

end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_visited(property)
    count1 =  $redis.sadd((current_user.id), (property.id).to_s)
  end

  def visited_property_delete(property)
    users = User.all
    users.each do |user|
      if ($redis.sismember(user.id, (property.id).to_s))
        $redis.srem(user.id, (property.id).to_s)
      end
    end
  end

end

app/views/properties/_form.html.erb
<tr>
  <th>
    <span><%= f.label :title %></span>
    <span><%= f.text_field :title %></span>
  </th>
  <th>
    <span><%= f.radio_button(:rooms, '1RK') %><%= f.label(:rooms, '1RK') %></span>
    <span><%= f.radio_button(:rooms, '1BHK') %><%= f.label(:rooms, '1BHK') %></span>
    <span><%= f.radio_button(:rooms, '2BHK') %><%= f.label(:rooms, '2BHK') %></span>
    <span><%= f.radio_button(:rooms, '3BHK') %><%= f.label(:rooms, '3BHK') %></span>
    <span><%= f.radio_button(:rooms, '4BHK') %><%= f.label(:rooms, '4BHK') %></span>
    <span><%= f.radio_button(:rooms, '4BHK+') %><%= f.label(:rooms, '4BHK+') %></span>
  </th>
</tr>
<tr>
  <th>
    <span><%= f.label :bedrooms %></span>
    <span><%= f.select(:bedrooms, ['1','2','3','4','5','6+']) %></span>
  </th>
  <th>
    <span><%= f.label :bathrooms %></span>
    <span><%= f.select(:bathrooms, ['1','2','3','4+']) %></span>
  </th>
</tr>
<tr>
  <th>
    <%= f.label :description %>
    <p><%= f.text_area :description %></p>
  </th>
  <th>
    <span><%= f.label :category %></span>
    <span><%= f.select(:category, ['Apartment','Hotel','Plot','Bunglow','House','Office']) %></span>
  </th>
</tr>

<tr>
  <td>
    <span class="picture">
      <strong>Upload Picture:</strong>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
  </td>
</tr>
<tr>
  <th>
    <span><%= f.label :city %></span>
    <span><%= f.text_field :city %></span>
  </th>
  <th>
    <span><%= f.label :location %></span>
    <span><%= f.text_field :location %></span>
  </th>
</tr>
<tr>
  <th>
    <span><%= f.label :price %></span>
    <span><%= f.text_field :price %></span>
  </th>
  <th>
    <span><%= f.label :area %></span>
    <span><%= f.text_field :area %></span>
  </th>
</tr>
<tr>
  <th>
    <span><%= f.label :owner %></span>
    <span><%= f.text_field :owner %></span>
  </th>
  <th>
    <span><%= f.label :contact %></span>
    <span><%= f.text_field :contact %></span>
  </th>
</tr>
<tr>
  <th><%= f.submit %></th>
</tr>

app/views/properties/adminUser.html.erb
<% if @properties.empty? %>
  <h3><%= No Any Property to Show %></h3>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>Property</th>
      <th>Added By</th>
      <th>Current Status</th>
      <th>Modify</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |p| %>
    <tr>
      <td><%= link_to p.title, property_path(p) %></td>
      <td><%= link_to p.user.name, p.user, class: "btn btn-lg-primary", style: "background-color:yellow; border:1px solid brown; color:brown;" %></td>
      <td><%= p.status %></td>
      <td><%= link_to "Modify Add", edit_property_path(p), class: "btn btn-lg-primary", style: "background-color:pink; border:1px solid blue; color:blue;" %></td>
      <td><%= link_to "Remove", property_path(p), method: :delete, data: { confirm: "Are You Sure?"} , class: "btn btn-lg-primary", style: "background-color:white; border:1px solid black; color:black;" %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/properties/edit.html.erb
<h1>Update your Add</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for (@property) do |f| %>
    <p>
      <%= f.label :status %>
      <% if @property.owner_type =="I need a Property" %>
        <%= f.select(:status, ['Needed','Got Property','Not needed Anymore']) %>
      <% else %>
        <% if @property.info == "For Sale" %>
          <%= f.select(:status, ['Available','Sold']) %>
        <% else %>
          <%= f.select(:status, ['Available','Rented']) %>
        <% end %>
      <% end %>
    </p>

    <%= render 'shared/error_messages', obj: @property %>
    <table class="table" id="view" style="border:1px solid blue;">
      <%= render 'form', f: f %>
    </table>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  $('#property_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/properties/index.html.erb
<% if @user.properties.empty? %>
  <h2 class="text-center"> You don't have any Active Property Add </h2>
<% else %>
<div>
  <table class="table" id="active-ads">
    <% @user.properties.each do |prop| %>
    <tr>
      <th>
        <%if prop.picture? %>
        <%= image_tag(prop.picture, style: "display:inline; height:105px; width:200px;") %>
        <% else %>
        <%= image_tag("no-thumb.jpg", style: "display:inline; height:105px; width:200px;") %>
        <% end %>
      </th>

      <% if current_user.is_admin? %>
        <th> <%= link_to prop.title, admin_property_path(current_user,prop) %> </th>
      <% else %>
        <th> <%= link_to prop.title, user_property_path(current_user,prop) %> </th>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>
<% end %>

app/views/properties/new.html.erb
<h1>Post a New Add</h1>
<%= form_for ([@user, @user.properties.build]) do |f| %>

  <%= render 'shared/error_messages', obj: @property %>

  <table class="table" id="view" style="border:1px solid blue;">
    <tr>
      <th>
        <span><%= f.label :info %></span>
        <span><%= f.select(:info, ['For Rent','For Sale']) %></span>
      </th>
    </tr>
    <tr>
      <th>
        <span><%= f.label(:owner_type, 'I need a Property')  %></span>
        <span><%= f.radio_button(:owner_type, 'I need a Property', checked: true) %></span>

        <span><%= f.label(:owner_type, 'I have a Property')  %></span>
        <span><%= f.radio_button(:owner_type,'I have a Property') %></span>
      </th>
    </tr>
    <%= render 'form', f: f %>
  </table>
<% end %>

<script type="text/javascript">
  $('#property_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/properties/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table" id="view" style="border:1px solid blue;">
      <tr>
        <th>Title:</th>
        <td><strong><%= @property.title %></strong></td>
      </tr>
      <tr>
        <% if @property.picture? %>
          <%= image_tag @property.picture.url %>
        <% else %>
          <%= image_tag("no-thumb.jpg") %>
        <% end %>
      </tr>
      <tr>
        <th>Current Status:</th>
        <td><strong><%= @property.status %></strong></td>
        <th><%= @property.info %></th>
      </tr>
      <tr>
        <th>City:</th>
        <td><%= @property.city %></td>
        <th>Location:</th>
        <td><%= @property.location %></td>
      </tr>
      <tr>
        <th>Rooms:</th>
        <td><%= @property.rooms %></td>
        <th>Bedrooms:</th>
        <td><%= @property.bedrooms %></td>
        <th>Bathrooms:</th>
        <td><%= @property.bathrooms %></td>
      </tr>
      <tr>
        <th>Description:</th>
        <td><%= @property.description %></td>
      </tr>
      <tr>
        <th>Category:</th>
        <td><%= @property.category %></td>
      </tr>
      <tr>
        <th>Area( sqft ):</th>
        <% if @property.area %>
          <td><%= @property.area %></td>
        <% else %>
          <td>Not Specified</td>
        <% end %>
        <th>Price( INR ):</th>
        <% if @property.price %>
          <td><%= @property.price %></td>
        <% else %>
          <td>Not Specified</td>
        <% end %>
      </tr>
      <tr>
        <th>Owner:</th>
        <td><%= @property.owner %></td>
        <th>Contact info:</th>
        <td><%= @property.contact %></td>
      </tr>
      <tr>
        <th>Owner Type:</th>
        <td><%= @property.owner_type %></td>
      </tr>
      <tr>
        <th>Added By:</th>
        <td><%= @property.user.name %></td>
      </tr>
    </table>
  </div>

  <div class="col-sm-4">
    <p> Total viewers: <%= @property.viewers %></p>
    <p>Overall Rating:
      <% avg_rating = @property.reviews.where(status: "Approve").average(:rating) %>
      <% if avg_rating %>
        <%= avg_rating %>
      <% else %>
        <span>Not Rated Yet</span>
      <% end %>
    </p>
    <% if current_user && (current_user == @property.user || current_user.is_admin) %>
    <p>
      <%= link_to "Modify Add", edit_user_property_path(current_user,@property) %>
    </p>
    <p>
      <%= link_to "Delete Add", user_property_path(current_user,@property), method: :delete, data: { confirm: "Are You Sure?"} %>
    </p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <% if current_user && current_user != @property.user %>
      <%= link_to "Review Add", new_property_review_path(@property) %>
      <% if @favourite %>
        <% msg = "Update Favourites" %>
      <% else %>
        <% msg = "Add Favourites" %>
      <% end %>
      <%= form_for (@favourite) || ([@property, @property.favourites.build]) do |f| %>
        <%= f.label :interested,  "Interested" %>
        <%= f.check_box(:interested) %>

        <%= f.submit msg %>

      <% end %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <p>Share this Property</p>
    <p><%= social_share_button_tag("My Home Page", :url => "http://commonfloorclone.com") %></p>
  </div>
</div>

<br>

<div class="row">
  <div class="col-sm-6 text-center">
    <% unless @property.reviews.empty? %>
      <strong>User Reviews for this Property:</strong>
      <table>
        <% f = false %>
        <% @property.reviews.each do |r| %>
          <% if r.status == "Approve" %>
          <% f = true %>
          <tr>
            <th>User:</th>
            <td><%= r.user.name %></td>
          </tr>
          <tr>
            <th>Rating:</th>
            <td><%= r.rating %></td>
          </tr>
          <tr>
            <th>Comments:</th>
            <td><%= r.comment %></td>
          </tr>
          <% end %>
        <% end %>
        <% unless f %>
          <p>Reviews are given but yet not approved</p>
        <% end %>
      </table>
    <% else %>
      <p>No any Reviews are given for this Property</p>
    <% end %>
  </div>
</div>