config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'auth/:provider/callback', to: 'sessions#omni'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/signup',  to: 'users#create'
  get '/admin/AllProperties', to: 'properties#adminUser'
  get '/search', to: 'static_pages#search'
  resources :users, :admins do
    resources :properties, :reviews
  end

  resources :properties do
    resources :reviews, :favourites
  end
  resources :admins do
    resources :users
    get :reviews, to: 'reviews#index'
  end
  resources :reviews do
    get 'approval'
    patch 'approve'
    get 'userReview', on: :collection
  end
  resources :reviews, :properties, :favourites
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :require_login, only: [:show]
  before_action :admin_login, only: [:index, :approval]
  before_action :correct_review, only: [:edit, :delete, :update, :approve, :approval]

  def index
    @reviews = Review.all
  end

  def userReview
    @reviews = current_user.reviews
  end

  def new
    @property = Property.find(params[:property_id])
    @review = Review.new
  end

  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.create(params.require(:review).permit(:rating,:comment))
    @review.user_id = current_user.id
    if @review.save
      flash[:success] = "Review Submitted"
      redirect_to property_review_path(@property,@review)
    else
      render 'new'
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def approval
    @review = Review.find(params[:review_id])
  end

  def approve
    @review = Review.find(params[:review_id])
    if @review.update_attributes(params.require(:review).permit(:status))
      @review.approved_by = current_user.id
      @review.save
      flash[:success] = "Review is #{@review.status}"
      redirect_to reviews_path
    else
      render 'approval'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(params.require(:review).permit(:rating, :comment))
      @review.status = 'Pending'
      @review.approved_by = ''
      @review.save
      flash[:success] = "Review Status Updated, It will be Public after Admin's Approval"
      redirect_to userReview_reviews_path
    else
      render 'edit'
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    flash[:success] = "Review Removed"
    redirect_to userReview_reviews_path
  end

private
  def correct_review
    unless (current_user.is_admin)
      @review = Review.find(params[:id])
      if current_user != @review.user
        flash[:danger] = "You are Not Authorize to this Review Operations"
        redirect_to root_path
      end
    else
      @review = Review.find(params[:review_id])
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= render 'shared/error_messages', obj: rev %>

<p>
  <%= f.label :rating %>
  <p><%= f.number_field(:rating, in: 0..5) %></p>

</p>

<p>
  <%= f.label :comment %>
  <p><%= f.text_area :comment %></p>
</p>

<%= f.submit %>

app/views/reviews/approval.html.erb
<h1>Review Details</h1>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @review.user.name, admin_user_path(current_user, @review.user_id) %>
</p>
<p>
  <strong>Property:</strong>
  <%= link_to @review.property.title, admin_property_path(current_user, @review.property_id) %>
</p>

<p>
  <strong>Admin Approval Status:</strong>
  <p><%= @review.status %></p>
</p>

<p>
  <%= form_for (@review), url: review_approve_path(@review), method: 'PATCH' do |f| %>
    <%= f.label("Reject", style:"color:red;") %>
    <%= f.radio_button(:status, "Reject") %>
    <%= f.label("Approve", style:"color:green;") %>
    <%= f.radio_button(:status, "Approve") %>
    <p><%= f.submit "Update Status" %></p>

  <% end %>
</p>

app/views/reviews/edit.html.erb
<h1>Edit Review for the Property</h1>

<%= form_for (@review) do |f| %>

  <%= render 'form', rev: @review, f: f %>

<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<% unless @reviews.empty? %>
<table class="table">
  <tr>
    <th>Property</th>
    <th>Property Added By</th>
    <th>Reviewed By</th>
    <th>Review Status:</th>
    <th>Rating</th>
    <th>Comments</th>
    <th>View Review</th>
  </tr>
  <% @reviews.each do |rev| %>
    <tr>
      <td>
        <%= link_to rev.property.title, admin_property_path(current_user,rev.property_id), class: "btn btn-lg-primary", style:"font-size:22px;" %>
      </td>
      <td>
        <%= link_to rev.property.user.name, admin_user_path(current_user,rev.property.user_id), class: "btn btn-lg-primary", style: "background-color:yellow; border:1px solid brown; color:brown;"  %>
      </td>
      <td>
        <%= link_to rev.user.name, admin_user_path(current_user, rev.user_id), class: "btn btn-lg-primary", style: "background-color:yellow; border:1px solid brown; color:brown;" %>
      </td>
      <td style="font-size:16px; font-weight:bold;"><%= rev.status %></td>
      <td style="font-size:22px; color:red;">
        <%= rev.rating   %>
      </td>
      <td style="font-size:22px; color:green;">
        <%=  rev.comment   %>
      </td>
      <td><%= link_to "View Review", review_approval_path(rev), class: "btn btn-lg-primary", style: "background-color:white; border:1px solid black; color:black;" %> </td>
    </tr>
  <% end %>
</table>
<% else %>
  <p>No any Reviews yet added</p>
<% end %>

app/views/reviews/new.html.erb
<h1>Review this Property</h1>

<%= form_for ([@property, @property.reviews.build]) do |f| %>
  <%= render 'form', rev: @review, f: f %>

<% end %>

app/views/reviews/show.html.erb
<h1>Review Details</h1>

<p>
  <strong>Rating:</strong>
  <%= r.rating %>
</p>
<p>
  <strong>Comment:</strong>
  <%= r.comment %>
</p>

app/views/reviews/userReview.html.erb
<% unless @reviews.empty? %>
  <% @reviews.each do |r| %>
  <p>
    <strong>Rating:</strong>
    <%= r.rating %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= r.comment %>
  </p>
  <p>
    <%= link_to r.property.title, r.property %>
  </p>

  <p> <%= link_to "Edit Your Review", edit_user_review_path(current_user,r) %> </p>
  <p> <%= link_to "Remove Comment", user_review_path(current_user,r), method: :delete, data: { confirm: "Are You Sure?"} %> </p>
  <% end %>
<% else %>
  <p class="text-center">You havn't Reviewed any Property</p>
<% end %>