config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'auth/:provider/callback', to: 'sessions#omni'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/signup',  to: 'users#create'
  get '/admin/AllProperties', to: 'properties#adminUser'
  get '/search', to: 'static_pages#search'
  resources :users, :admins do
    resources :properties, :reviews
  end

  resources :properties do
    resources :reviews, :favourites
  end
  resources :admins do
    resources :users
    get :reviews, to: 'reviews#index'
  end
  resources :reviews do
    get 'approval'
    patch 'approve'
    get 'userReview', on: :collection
  end
  resources :reviews, :properties, :favourites
    
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-default nav-cus">
  <div class="container con-cus">
    <ul class="pull-right">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="container gap-bottom" style="background-color:black; padding-bottom:10px;">
   <%= link_to image_tag( "commonfloor logo.png" ), root_path, id: "logo" %>
   <div style="float:right; ">
     <% if logged_in? %>
      <% if current_user.is_admin %>
        <%= link_to "Post a Free Add", new_admin_property_path(current_user), class: "btn btn-lg btn-primary hidden-xs", style: "margin-top:10px;"%>
      <% else %>
        <%= link_to "Post a Free Add", new_user_property_path(current_user), class: "btn btn-lg btn-primary hidden-xs", style: "margin-top:10px;" %>
      <% end %>
    <% else %>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary hidden-xs", style: "margin-top:10px;" %>
      <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary hidden-xs", style: "margin-top:10px;" %>
    <% end %>
   </div>
   <button type="button" id="mobile_menu" class="navbar-toggle" data-toggle="collapse" data-target="#site_navigation">
     <%= image_tag( "Menu(Mobile).png")%>
   </button>
 </header>
 <div class="container" style="padding-left:0px; padding-right:0px;">
   <nav class="collapse navbar-collapse gap-bottom" id="site_navigation">

     <ul class="nav navbar-nav">
       <li><%= link_to "Home", root_path %></li>
       <li><%= link_to "Help", help_path %></li>
       <% if logged_in? %>
        <% if current_user.is_admin? %>
          <li><%= link_to "Users", admin_users_path(current_user) %></li>
          <li><%= link_to "Properties", admin_AllProperties_path %></li>
          <li><%= link_to "Reviews", admin_reviews_path(current_user) %></li>
        <% end %>
      <% end %>
     </ul>
     <% if logged_in? %><!-- Profile Dropdown menu for Desktop and Tab view -->
      <span class="dropdown hidden-xs" style="float:right; position:relative; right:50px;">
        <button class="dropdown-toggle" data-toggle="dropdown" style="margin-top:5px;">
          Account <b class="caret"></b>
        </button>
        <ul class="dropdown-menu" >
          <% if current_user.is_admin? %>
            <li><%= link_to "Profile", admin_user_path(current_user,current_user) %></li>
            <li><%= link_to "Settings", edit_admin_user_path(current_user,current_user) %></li>
            <li><%= link_to "Active Ads", admin_properties_path(current_user) %></li>
            <% else %>
              <li><%= link_to "Profile", current_user %></li>

              <li><%= link_to "Settings", edit_user_path(current_user) %></li>

              <li><%= link_to "Active Ads", user_properties_path(current_user) %></li>

             <% end %>
             <li><%= link_to "Your Reviews", userReview_reviews_path %></li>
             <li><%= link_to "Favourites", favourites_path %></li>
             <li class="divider"></li>
             <li>
               <%= link_to "Log out", logout_path, method: :delete %>
             </li>
           </ul>
         </span>
      <% end %>
   </nav>
 </div>

<div class="continer visible-xs gap-bottom"> <!-- Profile Dropdown menu for Mobile view -->
  <% if logged_in? %>
    <span class="dropdown visible-xs" style="float:left; margin-left:15px;">
      <button class="dropdown-toggle" data-toggle="dropdown" style="margin-top:5px;">
        Account <b class="caret"></b>
      </button>
      <ul class="dropdown-menu" >
        <% if current_user.is_admin? %>
          <li><%= link_to "Profile", admin_user_path(current_user,current_user) %></li>
          <li><%= link_to "Settings", edit_admin_user_path(current_user,current_user) %></li>
          <li><%= link_to "Active Ads", admin_properties_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Profile", current_user %></li>

          <li><%= link_to "Settings", edit_user_path(current_user) %></li>

          <li><%= link_to "Active Ads", user_properties_path(current_user) %></li>

        <% end %>
          <li><%= link_to "Your Reviews", userReview_reviews_path %></li>
          <li><%= link_to "Favourites", favourites_path %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li>
      </ul>
    </span>
    <% if current_user.is_admin %>
      <%= link_to "Post a Free Add", new_admin_property_path(current_user), class: "btn btn-lg btn-primary", style: "width:45%; float:right; margin-right:15px;"%>
    <% else %>
      <%= link_to "Post a Free Add", new_user_property_path(current_user), class: "btn btn-lg btn-primary", style: "width:45%; float:right; margin-right:15px;" %>
    <% end %>
  <% else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", style: "width:45%; margin-left:15px;"%>
    <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary", style: "width:45%; float:right; margin-right:15px;"%>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container footer-gap">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>